### ISSUE TITLE
Add a new ContextModel for substitutables string

### ISSUE THREAD

**Issue by Alteoris** [mathieumack/OpenXMLSDK.Engine#187]
I need a new ContextModel object to substitute a string with other values.
The values can be of any type managed by the Report Engine and can also be a substitutable object with some values.
Please ensure that the values are managed with the current behavior (like the date formatting or the one for the number).

**Comment by mathieumack** [comment]
@DamienSAVOYAT Could you check that this Issue is still valid ?

**Comment by DamienSAVOYAT** [comment]
Ok, this is issue is fixed. I close it.
