### ISSUE TITLE
Add hyperlink to image model

### ISSUE THREAD

**Issue by TataneCode** [mathieumack/OpenXMLSDK.Engine#234]
For reports purpose, we need to have clickable image. The aim of the enhancement is to add an hyperlink property to the "Image" model.

**Comment by mathieumack** [comment]
Hello, 
You can fork the project, make your evolution and create a pull request to this repository.
As soon as the pull request is validated, a new package version will be generate to nuget ;)
Feel free to post your questions on this thread if needed.

To notice : Please do not include any customer or personal informations on the source code/tests or comments on issues.

**Comment by TataneCode** [comment]
Thanks Mathieu. I'm not sure I have the required permission on the repo, I cannot push my branch on your repo.

Failed to push to the remote repository. See the Output window for more details.
Switched to branch 'feature/234-image_add_hyperlink'
Checked out feature/234-image_add_hyperlink
Pushing feature/234-image_add_hyperlink
Error encountered while pushing branch to the remote repository: Git failed with a fatal error.
Git failed with a fatal error.
unable to access 'https://github.com/mathieumack/OpenXMLSDK.Engine.git/': The requested URL returned error: 403

**Comment by mathieumack** [comment]
Yes beacause you have to fork the project, and make your evolution on your own account before create the pull request to the main repo.
More informations : https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

**Comment by mathieumack** [comment]
Quick analyzis about your need : 
I think that the best solution was more to update the [Hyperlink](https://github.com/mathieumack/OpenXMLSDK.Engine/blob/master/src/OpenXMLSDK.Engine/Word/ReportEngine/Models/Hyperlink.cs) object with a Content field that can be a text, a table, an image ...
Instead updating Image with an Hyperlink. 
By updating the content of the hyperlink you will be able to update only the [render of the hyperlink] (https://github.com/mathieumack/OpenXMLSDK.Engine/blob/master/src/OpenXMLSDK.Engine/Word/ReportEngine/Renders/HyperlinkExtensions.cs) and it will reduce impact on the SDK.
